name: Haskell CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.2.4"
          cabal-version: "3.6.2.0"

      - name: Build
        run: |
          cabal update
          cabal build --enable-tests --enable-benchmarks exe:mono-tools
