name: Release

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: "9.2.4"
          cabal-version: "3.6.2.0"

      - name: Freeze
        run: |
          cabal freeze

      - uses: actions/cache@v3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Build
        id: build
        run: |
          cabal build exe:mono-tools
          echo "path=$(cabal list-bin mono-tools)" >> $GITHUB_OUTPUT
